### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by minad** [slim-template/slim-rails#109]
ping @leogalmeida

**Comment by minad** [comment]
If this is the case and someone is interested in taking over, please say so :)

**Comment by Salzig** [comment]
i would love to hear @leogalmeida opinion.

**Comment by Salzig** [comment]
maybe also @minad opinion. :)

**Comment by januszm** [comment]
I need it for my current project so I can volunteer ;)

I have to choose between HAML and Slim at this very moment and I'm leaning towards Slim only because it is very similar to Jade/Pug and seems cleaner. It looks like a nice joint between the Rails and JS Frameworks world. However, I'm aware that I could also use HAML with Gulp in JS projects. Anyway, If this is true and Slim is actively maintained, I can take care of maintaining the slim-rails gem so we're always up-to-date with new Rails releases.

**Comment by minad** [comment]
@januszm Could you also look into the other rails-related issues? I've seen you opened some other issues at the slim repository

**Comment by januszm** [comment]
@minad yeah we need to fix error reporting, it's broken in Rails 5, not sure about Rails 4.x, I didn't have time to test it.

**Comment by minad** [comment]
@januszm I added you

**Comment by minad** [comment]
and also you @Salzig

**Comment by Salzig** [comment]
to what exactly?

**Comment by minad** [comment]
@Salzig I invited you to this repository, but you didn't accept the invitation yet.

**Comment by Salzig** [comment]
@januszm and @salzig are working on it. closed for now.
