### ISSUE TITLE
Action Text: Rich Text Content displayed as raw html

### ISSUE THREAD

**Issue by diabolo** [slim-template/slim-rails#175]
Sample app: https://github.com/diabolo/r7dhhblog look at no-slim branch (add a post and see it displayed)

Slim is displaying action text rich text fields as raw html.

Rails 7
Ruby 3.0.3

With a partial _rich_text_content.html.erb 

```
<%= @post.content %>
```

and a view posts.html.slim with

```
...
strong Content:
p = @post.content
p == @post.content
p = render 'rich_text_content'
```

the bottom two render the action text. The top one renders raw html.

Is this intentional?

**Comment by januszm** [comment]
Hi @diabolo , check the `Output without HTML escaping ==` section of SLIM documentation at https://www.rubydoc.info/gems/slim/frames#output-without-html-escaping . It looks like in the second case with `==` pre-rendered  is not escaped. This looks like a more general Slim template question rather than slim-rails, see: https://github.com/slim-template/slim/issues
